apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: poi-rs

spec:
  replicas: 1
  selector: 
    matchLabels:
      poi: minam
  template:
    metadata:
      labels:
        poi: minam
    spec:
      volumes:
        - name: html
          configMap:
            name: poi-config-html
            items:
              - key: poi.html
                path: rier.html
      containers:
        - name: poid4
          image: poistargram/html
          args: ["4444"]
          volumeMounts: 
            - name: html
              mountPath: /poi/rier
          ports:
            - name: four
              containerPort: 4444
