apiVersion: v1
kind: Pod
metadata:
  name: poid
spec:
  containers:
    - name: poistargram
      image: poistargram/poid
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
